<a href="https://colab.research.google.com/github/AjeySrini/AI_Projects/blob/main/Healthcare_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

data = {
    'patient_id': [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,101,107,118,119,120],

    'age': ['25','34',None,'45','29',None,'38','52','27','41',
            '33','unknown','48','26','35','25','38','31',None,'44'],

    'weight': ['70','65','80',None,'75',None,'68','90','72','85',
               '78',None,'82','69','N/A','70','68','74',None,'88'],

    'blood_pressure': [120,130,None,140,125,None,135,None,118,145,
                       128,None,138,122,None,120,135,126,None,142],

    'medication': ['Aspirin','Metformin','Lisinopril',None,'Aspirin',
                   'Metformin','Lisinopril','Aspirin',None,'Metformin',
                   'Lisinopril','Aspirin',None,'Metformin','Aspirin',
                   'Aspirin','Lisinopril','Metformin','Aspirin',None],

    'insurance_provider': ['Blue Cross','Aetna','Cigna','UnitedHealth',None,
                           'Blue Cross','Aetna','Cigna','UnitedHealth','Blue Cross',
                           'Aetna',None,'UnitedHealth','Blue Cross','Aetna',
                           'Blue Cross','Aetna','Cigna','UnitedHealth',None]
}

df = pd.DataFrame(data)

df.head()

   patient_id   age weight  blood_pressure  medication insurance_provider
0         101    25     70           120.0     Aspirin         Blue Cross
1         102    34     65           130.0   Metformin              Aetna
2         103  None     80             NaN  Lisinopril              Cigna
3         104    45   None           140.0        None       UnitedHealth
4         105    29     75           125.0     Aspirin               None

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

In [3]:
df.isnull().sum()

patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [4]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

patient_id             0.0
age                   15.0
weight                20.0
blood_pressure        30.0
medication            20.0
insurance_provider    15.0
dtype: float64

In [5]:
df.duplicated().sum()

np.int64(2)

In [17]:
pd.to_numeric(df['age'], errors='coerce')

0     25.0
1     34.0
2     34.5
3     45.0
4     29.0
5     34.5
6     38.0
7     52.0
8     27.0
9     41.0
10    33.0
11    34.5
12    48.0
13    26.0
14    35.0
15    25.0
16    38.0
17    31.0
18    34.5
19    44.0
Name: age, dtype: float64

In [16]:
pd.to_numeric(df['weight'], errors='coerce')

0     70.0
1     65.0
2     80.0
3      NaN
4     75.0
5      NaN
6     68.0
7     90.0
8     72.0
9     85.0
10    78.0
11     NaN
12    82.0
13    69.0
14     NaN
15    70.0
16    68.0
17    74.0
18     NaN
19    88.0
Name: weight, dtype: float64

In [9]:
df.isnull().sum()

patient_id            0
age                   4
weight                5
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [47]:
df['insurance_provider'].fillna('Unknown')

0       Blue Cross
1            Aetna
2            Cigna
3     UnitedHealth
4          Unknown
5       Blue Cross
6            Aetna
7            Cigna
8     UnitedHealth
9       Blue Cross
10           Aetna
11         Unknown
12    UnitedHealth
13      Blue Cross
14           Aetna
17           Cigna
18    UnitedHealth
19         Unknown
Name: insurance_provider, dtype: category
Categories (5, object): ['Aetna', 'Blue Cross', 'Cigna', 'UnitedHealth', 'Unknown']

In [11]:
df.dtypes

patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

In [13]:
df['age'].fillna(df['age'].median())

0     25.0
1     34.0
2     34.5
3     45.0
4     29.0
5     34.5
6     38.0
7     52.0
8     27.0
9     41.0
10    33.0
11    34.5
12    48.0
13    26.0
14    35.0
15    25.0
16    38.0
17    31.0
18    34.5
19    44.0
Name: age, dtype: float64

In [14]:
df['weight'].fillna(df['weight'].median())

0     70.0
1     65.0
2     80.0
3     74.0
4     75.0
5     74.0
6     68.0
7     90.0
8     72.0
9     85.0
10    78.0
11    74.0
12    82.0
13    69.0
14    74.0
15    70.0
16    68.0
17    74.0
18    74.0
19    88.0
Name: weight, dtype: float64

In [18]:
df['blood_pressure'].fillna(df['blood_pressure'].median())

0     120.0
1     130.0
2     129.0
3     140.0
4     125.0
5     129.0
6     135.0
7     129.0
8     118.0
9     145.0
10    128.0
11    129.0
12    138.0
13    122.0
14    129.0
15    120.0
16    135.0
17    126.0
18    129.0
19    142.0
Name: blood_pressure, dtype: float64

In [52]:
df['medication'].fillna(df['medication'].mode()[0])

0        Aspirin
1      Metformin
2     Lisinopril
3        Aspirin
4        Aspirin
5      Metformin
6     Lisinopril
7        Aspirin
8        Aspirin
9      Metformin
10    Lisinopril
11       Aspirin
12       Aspirin
13     Metformin
14       Aspirin
17     Metformin
18       Aspirin
19       Aspirin
Name: medication, dtype: object

In [33]:
df['insurance_provider'].fillna('Unknown')

0       Blue Cross
1            Aetna
2            Cigna
3     UnitedHealth
4          Unknown
5       Blue Cross
6            Aetna
7            Cigna
8     UnitedHealth
9       Blue Cross
10           Aetna
11         Unknown
12    UnitedHealth
13      Blue Cross
14           Aetna
17           Cigna
18    UnitedHealth
19         Unknown
Name: insurance_provider, dtype: category
Categories (5, object): ['Aetna', 'Blue Cross', 'Cigna', 'UnitedHealth', 'Unknown']

In [22]:
df.isnull().sum()

patient_id            0
age                   0
weight                5
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [23]:
df[df.duplicated(keep=False)]

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna

In [24]:
df[df.duplicated(subset=['patient_id'], keep=False)]

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna

In [26]:
before_shape = df.shape

df = df.drop_duplicates(subset=['patient_id'], keep='first')

after_shape = df.shape

print("Shape before:", before_shape)
print("Shape after:", after_shape)

Shape before: (18, 6)
Shape after: (18, 6)

In [50]:
# Reload dataset
df_clean = pd.DataFrame(data)

print("Initial Shape:", df_clean.shape)

print("\nMissing values before cleaning:")
print(df_clean.isnull().sum())

print("\nDuplicate rows before cleaning:")
print(df_clean.duplicated(subset=['patient_id']).sum())

print("\nData types before cleaning:")
print(df_clean.dtypes)


df_clean['age'] = pd.to_numeric(df_clean['age'], errors='coerce')
df_clean['weight'] = pd.to_numeric(df_clean['weight'], errors='coerce')
df_clean['insurance_provider'] = df_clean['insurance_provider'].astype('category')


df_clean['age'] = df_clean['age'].fillna(df_clean['age'].median())
df_clean['weight'] = df_clean['weight'].fillna(df_clean['weight'].median())
df_clean['blood_pressure'] = df_clean['blood_pressure'].fillna(df_clean['blood_pressure'].median())
df_clean['medication'] = df_clean['medication'].fillna(df_clean['medication'].mode()[0])
df_clean['insurance_provider'] = df['insurance_provider'].fillna('Unknown')


df_clean = df_clean.drop_duplicates(subset=['patient_id'], keep='first')


print("\nFinal Shape:", df_clean.shape)

print("\nMissing values after cleaning:")
print(df_clean.isnull().sum())

print("\nDuplicate rows after cleaning:")
print(df_clean.duplicated(subset=['patient_id']).sum())

print("\nData types after cleaning:")
print(df_clean.dtypes)

Initial Shape: (20, 6)

Missing values before cleaning:
patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

Duplicate rows before cleaning:
2

Data types before cleaning:
patient_id              int64
age                    object
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

Final Shape: (18, 6)

Missing values after cleaning:
patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

Duplicate rows after cleaning:
0

Data types after cleaning:
patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

In [48]:
df['insurance_provider'].fillna('Unknown')

0       Blue Cross
1            Aetna
2            Cigna
3     UnitedHealth
4          Unknown
5       Blue Cross
6            Aetna
7            Cigna
8     UnitedHealth
9       Blue Cross
10           Aetna
11         Unknown
12    UnitedHealth
13      Blue Cross
14           Aetna
17           Cigna
18    UnitedHealth
19         Unknown
Name: insurance_provider, dtype: category
Categories (5, object): ['Aetna', 'Blue Cross', 'Cigna', 'UnitedHealth', 'Unknown']